08d55548-800a-4eda-a697-23e5a9f421f6:
  cost: 0.0
  selectedX: 1495
  originalWorldName: "minecraft:overworld"
  selectedY: 96
  selectedZ: -25
  selectedWorldId: "41fa8411-17c1-37f4-b08d-9586b63845d5"
  senderName: "FTL157"
  senderId: "08d55548-800a-4eda-a697-23e5a9f421f6"
  delay: 0
  originalWorldId: "41fa8411-17c1-37f4-b08d-9586b63845d5"
  originalY: 0
  originalZ: 0
  originalX: 0
  time: 1788423563039
  region: "default"
  selectedWorldName: "minecraft:overworld"
  attempts: 0
27a96fec-9b28-4152-b433-0dd8f085333b:
  cost: 0.0
  selectedX: -361
  originalWorldName: "minecraft:overworld"
  selectedY: 65
  selectedZ: 1367
  selectedWorldId: "41fa8411-17c1-37f4-b08d-9586b63845d5"
  senderName: "Tanrunn"
  senderId: "27a96fec-9b28-4152-b433-0dd8f085333b"
  delay: 0
  originalWorldId: "41fa8411-17c1-37f4-b08d-9586b63845d5"
  originalY: 0
  originalZ: 0
  originalX: 0
  time: 1788425319623
  region: "default"
  selectedWorldName: "minecraft:overworld"
  attempts: 0
