menuFiller: "menuFiller"
menuStyle: "menuStyle"
iconDefault: "iconDefault"
menuTitle: "menuTitle"
showDashboard: "showDashboard"
textFailurePrefix: "textFailurePrefix"
environmentIcons: "environmentIcons"
iconNetwork: "iconNetwork"
iconOnCooldown: "iconOnCooldown"
iconUnavailable: "iconUnavailable"
textSearching: "textSearching"
textSuccess: "textSuccess"
iconWorld: "iconWorld"
textUnavailable: "textUnavailable"
iconNoFunds: "iconNoFunds"
regionIcons: "regionIcons"
menuRows: "menuRows"
iconRegion: "iconRegion"
iconDashboard: "iconDashboard"
textReady: "textReady"
textQueued: "textQueued"
