["Async Config"]
	#Disables the mod. All entities are ticked on the main thread.
	disabled = false
	#Worker threads for parallel ticking. -1 = auto.
	# Default: -1
	# Range: > -1
	maxThreads = -1
	#Entities ticked on the main thread instead of in parallel.
	#Entity IDs or namespaces (*):
	#  - 'minecraft:zombie' = specific entity
	#  - 'minecraft:*'      = all entities in namespace
	synchronizedEntities = ["minecraft:tnt", "minecraft:experience_orb", "create:*", "minecraft:item"]
	#Enables async entity spawning. WARNING: incompatible with Carpet's lagFreeSpawning.
	enableAsyncSpawn = true
	#Experimental! Enables async random ticks.
	enableAsyncRandomTicks = false
