#Command names used by OPAC - Essentials.
#Changing a command name requires a full server restart.
[commands]
	#Root alias for Open Parties and Claims claim commands.
	#Use 1-32 lowercase letters, numbers, underscores or hyphens.
	claims = "claims"
	#Root alias for Open Parties and Claims party commands.
	#Use 1-32 lowercase letters, numbers, underscores or hyphens.
	party = "party"
	#Claims the chunk in which the executing player is standing.
	#Use 1-32 lowercase letters, numbers, underscores or hyphens.
	claim = "claim"
	#Unclaims the chunk in which the executing player is standing.
	#Use 1-32 lowercase letters, numbers, underscores or hyphens.
	unclaim = "unclaim"
	#Root command for OPAC - Essentials party chat.
	#Use 1-32 lowercase letters, numbers, underscores or hyphens.
	party_chat = "pchat"
