import json, os

with open('temp_subtle_en_us.json', 'r', encoding='utf-8') as f:
    en = json.load(f)

with open('temp_subtle_zh_cn.json', 'r', encoding='utf-8') as f:
    zh = json.load(f)

m = {}

m["subtitles.subtle_effects.block.monster_spawner.ambient"] = "刷怪笼噼啪作响"
m["subtitles.subtle_effects.block.monster_spawner.spawn_mob"] = "刷怪笼生成生物"
m["subtitles.subtle_effects.item.spawn_egg.spawn_mob"] = "生物从刷怪蛋中孵化"
m["commands.subtle_effects.subtle_effects.particles.display_bounding_boxes.enable.success"] = "正在显示粒子边界框"
m["commands.subtle_effects.subtle_effects.particles.display_bounding_boxes.disable.success"] = "不再显示粒子边界框"
m["chat.subtle_effects.prefix"] = "[微妙的影响]:"
m["chat.subtle_effects.anniversary.message"] = "今天是模组的 %s 岁生日！庆祝活动期间，玩家将获得派对帽！要禁用派对帽，请在 '%s' 配置类别中将 '启用彩蛋' 配置选项设为关闭。"
m["chat.subtle_effects.anniversary.message.click_event"] = "通用"
m["chat.subtle_effects.anniversary.message.click_event.tooltip"] = "点击打开配置菜单"
m["config.subtle_effects.conditions.config_disabled"] = "- 配置被以下值禁用：\"%s\""
m["config.subtle_effects.conditions.mod_not_loaded"] = "- 模组未加载：\"%s\""
m["config.subtle_effects.conditions.mod_loaded"] = "- 加载了不兼容的模组：\"%s\""
m["config.subtle_effects.blocks.sparks.lavaSparksDensity"] = "岩浆火花密度"
m["config.subtle_effects.blocks.sparks.brewingStandSparks"] = "酿造台火花"
m["config.subtle_effects.blocks.sparks.monsterSpawnerSparks"] = "刷怪笼火花"
m["config.subtle_effects.blocks.fallingBlocks.replaceDustWithBubblesUnderwater"] = "水下用气泡替换灰尘"
m["config.subtle_effects.blocks.fallingBlocks.replaceDustWithBubblesUnderwater.desc"] = "当方块落入水下时，将下落方块的灰尘粒子替换为气泡"
m["config.subtle_effects.blocks.commandBlockParticlesDensity"] = "命令方块粒子密度"
m["config.subtle_effects.blocks.cakeEatParticles"] = "吃蛋糕粒子"
m["config.subtle_effects.blocks.cakeEatSounds"] = "吃蛋糕音效"
m["config.subtle_effects.blocks.rainWaterRipples"] = "雨水涟漪"
m["config.subtle_effects.blocks.rainWaterRipples.desc"] = "下雨时是否在水面上生成涟漪粒子"
m["config.subtle_effects.blocks.rainWaterRipplesDensity"] = "雨水涟漪密度"
m["config.subtle_effects.blocks.underwaterBlockBreakBubbles"] = "水下破坏方块气泡"
m["config.subtle_effects.blocks.underwaterBlockBreakBubbles.desc"] = "在水下破坏方块时是否生成气泡"
m["config.subtle_effects.blocks.underwaterContainerBubblingGroup"] = "水下容器冒泡"
m["config.subtle_effects.blocks.decoratedPotsSpawnBubbles"] = "装饰罐生成气泡"
m["config.subtle_effects.blocks.decoratedPotsSpawnBubbles.desc"] = "装饰罐在水下时是否生成气泡"
m["config.subtle_effects.blocks.openingBarrelsSpawnsBubbles"] = "打开木桶生成气泡"
m["config.subtle_effects.blocks.openingChestsSpawnsBubbles"] = "打开箱子生成气泡"
m["config.subtle_effects.blocks.openingChestsSpawnsBubbles.desc"] = "箱子在水下打开时是否生成气泡"
m["config.subtle_effects.blocks.chestsOpenRandomlyUnderwaterFrequency"] = "箱子水下随机打开频率"
m["config.subtle_effects.blocks.chestsOpenRandomlyUnderwaterFrequency.desc"] = "箱子在水下随机打开的频率（秒）。设为 0 则禁用箱子水下随机打开"
m["config.subtle_effects.blocks.randomChestOpeningNeedsSoulSand"] = "随机打开箱子需要灵魂沙"
m["config.subtle_effects.blocks.dispenseItemBubbles"] = "发射物品气泡"
m["config.subtle_effects.blocks.dispenseItemBubbles.desc"] = "从发射器/投掷器/合成器在水下发射物品时是否生成气泡"
m["config.subtle_effects.blocks.rainIncreasesLeavesSpawningParticles"] = "雨水增加树叶粒子生成"
m["config.subtle_effects.blocks.rainIncreasesLeavesSpawningParticles.desc"] = "下雨时是否增加树叶方块生成的树叶粒子数量"
m["config.subtle_effects.blocks.purpleMonsterSpawnerParticles"] = "紫色刷怪笼粒子"
m["config.subtle_effects.blocks.purpleMonsterSpawnerParticles.desc"] = "将原版火焰粒子替换为与刷怪笼紫色眼睛匹配的紫色火焰粒子"
m["config.subtle_effects.blocks.monsterSpawnerSpawnMobSoundVolume"] = "刷怪笼生成生物音量"
m["config.subtle_effects.blocks.monsterSpawnerSpawnMobSoundVolume.desc"] = "刷怪笼生成生物时播放的音量"
m["config.subtle_effects.blocks.monsterSpawnerAmbientSoundVolume"] = "刷怪笼环境音量"
m["config.subtle_effects.entities.humanoids.potionRingsScale"] = "药水光环缩放"
m["config.subtle_effects.entities.humanoids.potionRingsAlpha"] = "药水光环透明度"
m["config.subtle_effects.entities.burning.smokeType"] = "烟雾类型"
m["config.subtle_effects.entities.burning.smokeDensity"] = "烟雾密度"
m["config.subtle_effects.entities.burning.flamesDensity"] = "火焰密度"
m["config.subtle_effects.entities.burning.flamesDensity.desc"] = "设为 0 则禁用"
m["config.subtle_effects.entities.burning.sparksDensity"] = "火花密度"
m["config.subtle_effects.entities.burning.sparksDensity.desc"] = "设为 0 则禁用"
m["config.subtle_effects.entities.burning.soundVolume"] = "音量"
m["config.subtle_effects.entities.burning.soundVolume.desc"] = "燃烧实体偶尔发出的嘶嘶声音量。设为 0 则禁用"
m["config.subtle_effects.entities.burning.entityBlocklist"] = "实体黑名单"
m["config.subtle_effects.entities.burning.overrideDyedFlamesEffects"] = "覆盖染色火焰效果"
m["config.subtle_effects.entities.burning.overrideDyedFlamesEffects.desc"] = "禁用染色火焰生成的岩浆火花效果"
m["config.subtle_effects.entities.splashes"] = "溅水"
m["config.subtle_effects.entities.splashes.splashEffects"] = "溅水效果"
m["config.subtle_effects.entities.splashes.splashEffects.desc"] = "实体落入原版液体时是否有溅水效果"
m["config.subtle_effects.entities.splashes.splashRipples"] = "溅水涟漪"
m["config.subtle_effects.entities.splashes.splashRipples.desc"] = "溅水后是否播放涟漪效果"
m["config.subtle_effects.entities.splashes.splashDroplets"] = "溅水水滴"
m["config.subtle_effects.entities.splashes.splashDropletSounds"] = "溅水水滴音效"
m["config.subtle_effects.entities.splashes.waterSplashBubbles"] = "溅水气泡"
m["config.subtle_effects.entities.splashes.waterSplashBubbles.desc"] = "水下是否爆发气泡"
m["config.subtle_effects.entities.splashes.explosionsCauseSplashes"] = "爆炸引起溅水"
m["config.subtle_effects.entities.splashes.explosionsCauseSplashes.desc"] = "爆炸在水/岩浆中时是否引起溅水效果"
m["config.subtle_effects.entities.splashes.splashOverlayTint"] = "溅水叠加层染色"
m["config.subtle_effects.entities.splashes.splashOverlayTint.desc"] = "溅水叠加层的染色强度"
m["config.subtle_effects.entities.splashes.splashOverlayAlpha"] = "溅水叠加层透明度"
m["config.subtle_effects.entities.splashes.splashOverlayAlpha.desc"] = "溅水叠加层的透明度。叠加层是水溅顶部的白色泡沫边缘。此配置也影响水溅涟漪效果。设为 0 则禁用叠加层"
m["config.subtle_effects.entities.splashes.splashVelocityThreshold"] = "溅水速度阈值"
m["config.subtle_effects.entities.splashes.splashVelocityThreshold.desc"] = "触发溅水所需的速度阈值"
m["config.subtle_effects.entities.splashes.entityBlocklist"] = "实体黑名单"
m["config.subtle_effects.entities.splashes.entityBlocklist.desc"] = "不会有溅水效果的实体列表"
m["config.subtle_effects.entities.splashes.secondarySplashesGroup"] = "二次溅水"
m["config.subtle_effects.entities.splashes.secondarySplash"] = "二次溅水"
m["config.subtle_effects.entities.splashes.secondarySplash.desc"] = "在初始溅水后播放第二次溅水效果"
m["config.subtle_effects.entities.splashes.secondarySplashRipples"] = "二次溅水涟漪"
m["config.subtle_effects.entities.splashes.secondarySplashRipples.desc"] = "二次溅水后是否播放涟漪效果"
m["config.subtle_effects.entities.splashes.secondarySplashVelocityThreshold"] = "二次溅水速度阈值"
m["config.subtle_effects.entities.splashes.secondarySplashVelocityThreshold.desc"] = "触发二次溅水所需的速度阈值。不能低于普通溅水速度阈值"
m["config.subtle_effects.entities.attackedChickenFeathers"] = "被攻击的鸡掉落羽毛"
m["config.subtle_effects.entities.attackedParrotFeathers"] = "被攻击的鹦鹉掉落羽毛"
m["config.subtle_effects.entities.attackedSnowGolemSnowflakes"] = "被攻击的雪人掉落雪花"
m["config.subtle_effects.entities.attackedSheepFluff"] = "被攻击的绵羊掉落绒毛"
m["config.subtle_effects.entities.attackedSlimeSlime"] = "被攻击的史莱姆掉落粘液"
m["config.subtle_effects.entities.dragonsBreathClouds"] = "龙息云"
m["config.subtle_effects.entities.dragonsBreathClouds.desc"] = "将滞留药水云效果应用于末影龙息"
m["config.subtle_effects.entities.underwaterEntityPoofBubbles"] = "水下实体出现气泡"
m["config.subtle_effects.entities.underwaterEntityPoofBubbles.desc"] = "实体在水下生成或死亡时，出现效果是否带有气泡"
m["config.subtle_effects.entities.improvedWetWolfShakeEffects"] = "改进湿狼抖水效果"
m["config.subtle_effects.entities.improvedWetWolfShakeEffects.desc"] = "改进狼抖水时的水效果"
m["config.subtle_effects.entities.improvedVillagerSweatingEffects"] = "改进村民流汗效果"
m["config.subtle_effects.entities.improvedVillagerSweatingEffects.desc"] = "改进袭击期间村民的流汗效果"
m["config.subtle_effects.entities.magmaCubeLandSparks"] = "岩浆怪落地火花"
m["config.subtle_effects.entities.magmaCubeLandSparks.desc"] = "岩浆怪落地时是否生成火花"
m["config.subtle_effects.entities.snowGolemStepSounds"] = "雪人脚步声"
m["config.subtle_effects.entities.snowGolemStepSounds.desc"] = "将雪人的脚步声替换为雪方块的脚步声"
m["config.subtle_effects.environment.geysers.flameGeyserSpawnableBlocks"] = "火焰间歇泉可生成方块"
m["config.subtle_effects.environment.geysers.flameGeyserSpawnableBlocks.desc"] = "火焰间歇泉可以在其上生成的方块ID列表，包括流体"
m["config.subtle_effects.environment.geysers.smokeGeyserSpawnableBlocks"] = "烟雾间歇泉可生成方块"
m["config.subtle_effects.environment.geysers.smokeGeyserSpawnableBlocks.desc"] = "烟雾间歇泉可以在其上生成的方块ID列表，包括流体"
m["config.subtle_effects.environment.geysers.bubbleGeyserSpawnableBlocks"] = "气泡间歇泉可生成方块"
m["config.subtle_effects.environment.geysers.bubbleGeyserSpawnableBlocks.desc"] = "气泡间歇泉可以在其上生成的方块ID列表，包括流体"
m["config.subtle_effects.environment.waterfalls"] = "瀑布"
m["config.subtle_effects.environment.waterfalls.waterfallsEnabled"] = "启用瀑布"
m["config.subtle_effects.environment.waterfalls.smallWaterfallsEnabled"] = "启用小瀑布"
m["config.subtle_effects.environment.waterfalls.waterfallUpdateFrequency"] = "瀑布更新频率"
m["config.subtle_effects.environment.waterfalls.waterfallUpdateFrequency.desc"] = "瀑布检查其有效性的频率（刻）。这可能是比较密集的过程，建议使用较高的值"
m["config.subtle_effects.environment.waterfalls.randomizeWaterfallParticleRotation"] = "随机化瀑布粒子旋转"
m["config.subtle_effects.environment.waterfalls.randomizeWaterfallParticleRotation.desc"] = "瀑布粒子是否随机旋转"
m["config.subtle_effects.environment.waterfalls.mediumWaterfallsGroup"] = "中等瀑布"
m["config.subtle_effects.environment.waterfalls.mediumWaterfallParticleDensity"] = "中等瀑布粒子密度"
m["config.subtle_effects.environment.waterfalls.mediumWaterfallHeightThreshold"] = "中等瀑布高度阈值"
m["config.subtle_effects.environment.waterfalls.mediumWaterfallHeightThreshold.desc"] = "瀑布被视为中等的高度（格）"
m["config.subtle_effects.environment.waterfalls.forceSpawnMediumWaterfallParticles"] = "强制生成中等瀑布粒子"
m["config.subtle_effects.environment.waterfalls.forceSpawnMediumWaterfallParticles.desc"] = "中等瀑布粒子是否无论玩家距离如何都可见"
m["config.subtle_effects.environment.waterfalls.largeWaterfallsGroup"] = "大型瀑布"
m["config.subtle_effects.environment.waterfalls.largeWaterfallsEnabled"] = "启用大型瀑布"
m["config.subtle_effects.environment.waterfalls.largeWaterfallParticleDensity"] = "大型瀑布粒子密度"
m["config.subtle_effects.environment.waterfalls.largeWaterfallHeightThreshold"] = "大型瀑布高度阈值"
m["config.subtle_effects.environment.waterfalls.largeWaterfallHeightThreshold.desc"] = "瀑布被视为大型的高度（格）"
m["config.subtle_effects.environment.waterfalls.forceSpawnLargeWaterfallParticles"] = "强制生成大型瀑布粒子"
m["config.subtle_effects.environment.waterfalls.forceSpawnLargeWaterfallParticles.desc"] = "大型瀑布粒子是否无论玩家距离如何都可见"
m["config.subtle_effects.items.itemRarity.particleDensity.desc"] = "物品周围生成的粒子密度"
m["config.subtle_effects.items.projectiles.enderPearlTrailDensity"] = "末影珍珠尾迹密度"
m["config.subtle_effects.items.projectiles.enderPearlTrailDensity.desc"] = "末影珍珠粒子尾迹的密度。设为 0 则禁用"
m["config.subtle_effects.items.fluidBucketUseParticles"] = "流体桶使用粒子"
m["config.subtle_effects.items.powderSnowBucketBlockPlaceSound"] = "粉雪桶方块放置音效"
m["config.subtle_effects.items.powderSnowBucketBlockPlaceSound.desc"] = "除了粉雪桶倒空音效外，是否还播放粉雪方块放置音效"
m["config.subtle_effects.items.lingeringPotionClouds"] = "滞留药水云"
m["config.subtle_effects.items.lingeringPotionClouds.desc"] = "将原版气泡漩涡粒子替换为缕缕云烟"
m["config.subtle_effects.items.splashPotionClouds"] = "喷溅药水云"
m["config.subtle_effects.items.splashPotionClouds.desc"] = "将原版气泡漩涡粒子替换为蓬松云朵"
m["config.subtle_effects.items.structureVoidItemMarker"] = "结构虚空物品标记"
m["config.subtle_effects.items.structureVoidItemMarker.desc"] = "使放置的结构虚空显示类似于放置的屏障，当玩家手持结构虚空物品时，世界中其他结构虚空将可见"
m["config.subtle_effects.items.armadilloBrushParticles"] = "犰狳刷毛粒子"
m["config.subtle_effects.items.armadilloBrushParticles.desc"] = "刷犰狳时是否生成粒子"
m["config.subtle_effects.items.spawnEggUseSoundVolume"] = "刷怪蛋使用音量"
m["config.subtle_effects.items.spawnEggUseSoundVolume.desc"] = "刷怪蛋使用音效的音量"
m["config.subtle_effects.items.spawnEggUseParticles"] = "刷怪蛋使用粒子"
m["config.subtle_effects.items.spawnEggUseParticles.desc"] = "使用刷怪蛋时是否在生物周围生成出现粒子。注意：由于客户端限制，此效果可能不会每次都出现"
m["config.subtle_effects.general.particleCullingBlocklist"] = "粒子裁剪黑名单"
m["config.subtle_effects.general.particleCullingBlocklist.desc"] = "不会被粒子裁剪系统裁剪的粒子列表。此列表应保持最小，主要用于裁剪时会损坏的粒子。已在世界中生成的粒子不受此配置更改的影响"
m["config.subtle_effects.general.allowUsingBlendedRenderType"] = "允许使用混合渲染类型"
m["config.subtle_effects.general.allowUsingBlendedRenderType.desc"] = "某些粒子使用自定义渲染类型来混合透明度。这可能导致与其他模组的视觉问题。此配置允许您禁用自定义渲染类型并改用默认透明度渲染类型。"
m["config.subtle_effects.general.spellParticlesUseBlendedRenderType"] = "法术粒子使用混合渲染类型"
m["config.subtle_effects.general.spellParticlesUseBlendedRenderType.desc"] = "将法术粒子更改为使用自定义混合渲染类型。这可能导致与其他模组的视觉问题。此配置允许您禁用自定义渲染类型并改用默认透明度渲染类型。如果'允许使用混合渲染类型'被禁用，则此配置被忽略。"
m["config.subtle_effects.general.fluidDropsEvaporationVolume.desc"] = "液滴粒子蒸发时发出的嘶嘶声音量"
m["config.subtle_effects.general.dropLandInFluidRipples"] = "液滴落入液体涟漪"
m["config.subtle_effects.general.dropLandInFluidRipples.desc"] = "当液滴粒子落入同类型液体会产生涟漪粒子"
m["config.subtle_effects.general.leavesGroup"] = "树叶"
m["config.subtle_effects.general.leavesLandOnGround"] = "树叶落在地面"
m["config.subtle_effects.general.leavesLandOnWater"] = "树叶落在水面"
m["config.subtle_effects.general.leavesLandingOnWaterRipples"] = "树叶落水的涟漪"
m["config.subtle_effects.general.leavesLandingOnWaterRipples.desc"] = "树叶落在水面时会产生涟漪粒子"
m["config.subtle_effects.general.leavesLandingOnWaterKeepMomentum"] = "树叶落水保持动量"
m["config.subtle_effects.general.leavesLandingOnWaterKeepMomentum.desc"] = "树叶落在水面时会保持部分动量"
m["config.subtle_effects.general.fallenLeavesLifeTime"] = "落叶寿命"
m["config.subtle_effects.general.fallenLeavesLifeTime.desc"] = "落叶在地面/水上停留的时间（刻），然后消失。数值会有一定随机化"
m["config.subtle_effects.general.rainIncreasesLeavesMovementSpeed"] = "雨水增加树叶移动速度"
m["config.subtle_effects.general.rainIncreasesLeavesMovementSpeed.desc"] = "在下雨和雷暴期间，树叶会增加移动速度"
m["config.subtle_effects.general.staticFlameBrightness"] = "静态火焰亮度"
m["config.subtle_effects.general.staticFlameBrightness.desc"] = "火焰粒子是否始终最大亮度，还是根据年龄和光照级别动态改变亮度"
m["config.subtle_effects.general.fireOverlayGroup"] = "火焰叠加层"
m["config.subtle_effects.general.fireOverlayHeight"] = "火焰叠加层高度"
m["config.subtle_effects.general.fireOverlayHeight.desc"] = "火焰叠加层在屏幕上的高度。0 为原版值"
m["config.subtle_effects.general.fireOverlayAlpha"] = "火焰叠加层透明度"
m["config.subtle_effects.general.fireOverlayAlpha.desc"] = "火焰叠加层的透明度。0.9 为原版值"
m["config.subtle_effects.general.fireOverlayAlphaWithFireResistance"] = "火焰抗性时火焰叠加层透明度"
m["config.subtle_effects.general.fireOverlayAlphaWithFireResistance.desc"] = "火焰抗性效果激活时火焰叠加层的透明度。0.9 为原版值"

merged = {**zh, **m}

print(f"英文键数: {len(en)}")
print(f"原有中文键数: {len(zh)}")
print(f"新增翻译键数: {len(m)}")
print(f"最终中文键数: {len(merged)}")
print(f"缺失键数: {len([k for k in en if k not in merged])}")

output_path = r"D:/Minecraft_III/Minecraft-Server/食韵筑家专用材质包v1.21.1/assets/subtle_effects/lang/zh_cn.json"
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(merged, f, ensure_ascii=False, indent=0)
print(f"文件已保存: {output_path}")

with open(output_path, 'r', encoding='utf-8') as f:
    verify = json.load(f)
print(f"JSON 有效: {len(verify)} 个键")

os.remove('temp_subtle_en_us.json')
os.remove('temp_subtle_zh_cn.json')
print("完成")
