package com.tanrunn.tcth.impl.brewing;

import java.util.HashMap;
import java.util.Map;

import org.jetbrains.annotations.Nullable;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.tanrunn.tcth.TCTHIntegration;
import com.tanrunn.tcth.api.brewing.BeverageTier;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.packs.resources.ResourceManager;
import net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener;
import net.minecraft.util.profiling.ProfilerFiller;
import net.minecraft.world.item.ItemStack;

/**
 * Loads the per-item beverage tier mapping from
 * {@code data/<ns>/beverage_tiers/items/<item-ns>/<path>.json} (phase 7B.1).
 *
 * <p>Each file contains exactly one of {@code {"tier": "COMMON"}} or
 * {@code {"tier": "T2"}} — generated by
 * {@code scripts/generate_brewer_data.py} from the authoritative 7A CSV.
 * The audit-only draft {@code data/tcth/brewer/tiers.json} (docs/presets) is
 * <em>never</em> read at runtime. Loading is atomic (a new immutable map is
 * swapped in on reload).
 */
public final class BeverageTierManager extends SimpleJsonResourceReloadListener {

    public static final String FOLDER = "beverage_tiers";
    private static final String ITEMS_PREFIX = "items/";

    private static final Gson GSON = new Gson();

    private static volatile Map<ResourceLocation, BeverageTier> tierByItem = Map.of();

    public BeverageTierManager() {
        super(GSON, FOLDER);
    }

    /** Resolves the tier for an item; {@link BeverageTier#UNKNOWN} when absent. */
    public static BeverageTier tierFor(ItemStack stack) {
        if (stack == null || stack.isEmpty()) {
            return BeverageTier.UNKNOWN;
        }
        ResourceLocation id = stack.getItem().builtInRegistryHolder().key().location();
        return tierByItem.getOrDefault(id, BeverageTier.UNKNOWN);
    }

    @Override
    protected void apply(Map<ResourceLocation, JsonElement> objects, ResourceManager manager,
                        ProfilerFiller profiler) {
        Map<ResourceLocation, BeverageTier> next = new HashMap<>();
        for (Map.Entry<ResourceLocation, JsonElement> entry : objects.entrySet()) {
            // key is the full file id, e.g. tcth:beverage_tiers/items/brewinandchewin/beer
            // item id = last two path segments: <ns>/<path>
            String key = entry.getKey().getPath();
            if (!key.startsWith(ITEMS_PREFIX)) {
                continue;
            }
            String itemPart = key.substring(ITEMS_PREFIX.length());
            int slash = itemPart.indexOf('/');
            if (slash <= 0 || slash == itemPart.length() - 1) {
                continue;
            }
            String itemNs = itemPart.substring(0, slash);
            String itemPath = itemPart.substring(slash + 1);
            ResourceLocation itemId = ResourceLocation.fromNamespaceAndPath(itemNs, itemPath);

            JsonObject root = entry.getValue().getAsJsonObject();
            if (!root.has("tier")) {
                continue;
            }
            String tierName = root.get("tier").getAsString();
            BeverageTier tier = switch (tierName) {
                case "COMMON" -> BeverageTier.COMMON;
                case "T2" -> BeverageTier.T2;
                default -> null;
            };
            if (tier != null) {
                next.put(itemId, tier);
            }
        }
        tierByItem = Map.copyOf(next);
        TCTHIntegration.LOGGER.info("[TCTH] Brewer tiers loaded: {} items ({} COMMON / {} T2)",
                next.size(),
                next.values().stream().filter(t -> t == BeverageTier.COMMON).count(),
                next.values().stream().filter(t -> t == BeverageTier.T2).count());
    }

    /** Test hook: replaces the tier map. */
    public static void setTierMapForTesting(@Nullable Map<ResourceLocation, BeverageTier> map) {
        tierByItem = map == null ? Map.of() : Map.copyOf(map);
    }

    /** Test hook: clears the tier map. */
    public static void resetForTesting() {
        tierByItem = Map.of();
    }
}
