shape: "shape"
displayName: "displayName"
worldBorderOverride: "worldBorderOverride"
vert: "vert"
requirePermission: "requirePermission"
version: "version"
spatialResolution: "spatialResolution"
world: "world"
activeChunkCap: "activeChunkCap"
price: "price"
cacheCap: "cacheCap"
networkReserveSize: "networkReserveSize"
override: "override"
backlogCacheCap: "backlogCacheCap"
