import json, os

with open('temp_distant_en_us.json', 'r', encoding='utf-8') as f:
    en = json.load(f)

t = {}

# === General ===
t["distanthorizons.title"] = "遥远的地平线"
t["distanthorizons.general.true"] = "是"
t["distanthorizons.general.false"] = "否"
t["distanthorizons.general.yes"] = "是"
t["distanthorizons.general.no"] = "否"
t["distanthorizons.general.back"] = "返回"
t["distanthorizons.general.next"] = "下一步"
t["distanthorizons.general.done"] = "完成"
t["distanthorizons.general.cancel"] = "取消"
t["distanthorizons.general.reset"] = "重置"
t["distanthorizons.general.spacer"] = ""
t["distanthorizons.general.apiOverride"] = "API 锁定"
t["distanthorizons.general.disabledByApi.@tooltip"] = "此选项由另一个模组通过 DH 的 API 控制，因此无法通过 UI 或配置文件更改。"
t["distanthorizons.general.unsupportedMcVersion"] = "版本锁定"
t["distanthorizons.general.unsupportedMcVersion.@tooltip"] = "DH 不支持在此版本的 Minecraft 上更改此选项。配置文件或 API 设置的值将被忽略。"

# === Updater ===
t["distanthorizons.updater.title"] = "遥远的地平线自动更新器"
t["distanthorizons.updater.updateAvailable"] = "§l有新更新可用！"
t["distanthorizons.updater.updateConfirmation"] = "§f是否要从 %s§f 更新到 %s§f？"
t["distanthorizons.updater.later"] = "暂不"
t["distanthorizons.updater.never"] = "不再显示"
t["distanthorizons.updater.update"] = "更新"
t["distanthorizons.updater.update.@tooltip"] = "本次更新模组（游戏关闭时更新）"
t["distanthorizons.updater.silent"] = "始终静默更新"
t["distanthorizons.updater.silent.@tooltip"] = "每次有可用更新时都会更新（§6警告§r：更新时不会提示您）"
t["distanthorizons.updater.waitingForClose"] = "遥远的地平线将在游戏重启后完成更新"

# === Config ===
t["distanthorizons.config.title"] = "遥远的地平线配置"
t["distanthorizons.config.client"] = "客户端"
t["distanthorizons.config.client.quickEnableRendering"] = "启用渲染"
t["distanthorizons.config.client.quickEnableRendering.@tooltip"] = "如果启用，遥远的地平线将在原版渲染距离之外渲染 LOD。"
t["distanthorizons.config.client.quickShowWorldGenProgress"] = "显示 LOD 生成/导入进度"
t["distanthorizons.config.client.quickShowWorldGenProgress.@tooltip"] = "如果启用，运行时将显示世界生成/导入进度。"
t["distanthorizons.config.client.qualityPresetSetting"] = "质量预设"
t["distanthorizons.config.client.qualityPresetSetting.@tooltip"] = "修改多项图形设置以快速改变遥远的地平线渲染质量。\n\n如果 GPU 使用率达到上限或出现帧率问题，请降低此设置。"
t["distanthorizons.config.client.threadPresetSetting"] = "CPU 负载"
t["distanthorizons.config.client.threadPresetSetting.@tooltip"] = "修改遥远的地平线使用的线程数。\n\n增加此设置将提高远程生成器速度和 LOD 加载速度，\n但也会增加 CPU/内存使用并可能引入卡顿。\n\n注意：这是相对于 CPU 的设置。\n它应该对 2 核 CPU 和 64 核 CPU 施加相同的压力。"
t["distanthorizons.config.client.optionsButton"] = "显示选项按钮"
t["distanthorizons.config.client.optionsButton.@tooltip"] = "在 FOV 按钮左侧显示配置按钮"

# === Advanced ===
t["distanthorizons.config.client.advanced"] = "高级选项"
t["distanthorizons.config.client.advanced.graphics"] = "图形"
t["distanthorizons.config.client.advanced.worldGenerator"] = "世界生成器"
t["distanthorizons.config.client.advanced.server"] = "服务器"
t["distanthorizons.config.client.advanced.lodBuilding"] = "LOD 构建"
t["distanthorizons.config.client.advanced.multiThreading"] = "多线程"
t["distanthorizons.config.client.advanced.logging"] = "日志"

# === Graphics Quality ===
t["distanthorizons.config.client.advanced.graphics.quality"] = "质量"
t["distanthorizons.config.client.advanced.graphics.quality.lodChunkRenderDistanceRadius"] = "LOD 区块渲染距离半径"
t["distanthorizons.config.client.advanced.graphics.quality.lodChunkRenderDistanceRadius.@tooltip"] = "遥远的地平线的渲染距离，以区块为单位。\n\n注意：这是一个尽力而为的数字。\n实际渲染距离可能高于或低于此数字，\n具体取决于您的其他图形设置。"
t["distanthorizons.config.client.advanced.graphics.quality.horizontalQuality"] = "LOD 衰减距离"
t["distanthorizons.config.client.advanced.graphics.quality.horizontalQuality.@tooltip"] = "这表示 LOD 质量下降之间的距离。\n\n较高的设置会增加下降之间的距离，\n但会增加内存和 GPU 使用。"
t["distanthorizons.config.client.advanced.graphics.quality.maxHorizontalResolution"] = "最大水平分辨率"
t["distanthorizons.config.client.advanced.graphics.quality.maxHorizontalResolution.@tooltip"] = "LOD 可以渲染的最大细节。\n\n§6最快：§r区块\n§6最精美：§r方块"
t["distanthorizons.config.client.advanced.graphics.quality.verticalQuality"] = "垂直质量"
t["distanthorizons.config.client.advanced.graphics.quality.verticalQuality.@tooltip"] = "LOD 如何表示悬垂物、洞穴、悬崖等。\n\n较高的选项会增加内存和 GPU 使用。"
t["distanthorizons.config.client.advanced.graphics.quality.useCameraPositionForQualityDropOff"] = "使用相机位置进行质量衰减"
t["distanthorizons.config.client.advanced.graphics.quality.useCameraPositionForQualityDropOff.@tooltip"] = "如果启用，DH 将在确定 LOD 质量衰减时尝试使用相机位置。\n如果禁用，DH 将使用玩家位置。\n\n启用有助于自由相机模组正确渲染。\n禁用有助于多相机模组正确渲染（例如沉浸式传送门或相机模组）。"
t["distanthorizons.config.client.advanced.graphics.quality.increaseQualityWhenZoomedIn"] = "放大时提高质量"
t["distanthorizons.config.client.advanced.graphics.quality.increaseQualityWhenZoomedIn.@tooltip"] = "如果启用，当相机放大时 LOD 质量会增加，\n例如使用望远镜或缩放模组时。\n\n只有通过相机视图可见的 LOD 会受到影响。\n\n放大时，LOD 将加载到与靠近它们时相同的细节级别。"
t["distanthorizons.config.client.advanced.graphics.quality.maxZoomQualityIncrease"] = "最大放大质量提升"
t["distanthorizons.config.client.advanced.graphics.quality.maxZoomQualityIncrease.@tooltip"] = "放大可以将 LOD 质量提高多少个细节级别。\n较高的数字允许更强的缩放渲染更清晰的地形，\n但在放大时会增加内存和 GPU 使用。\n\n原版望远镜需要 4 个细节级别才能达到完整质量。"
t["distanthorizons.config.client.advanced.graphics.quality.horizontalScale"] = "水平缩放"
t["distanthorizons.config.client.advanced.graphics.quality.horizontalScale.@tooltip"] = "LOD 质量下降的速度。\n\n较大的数字会改善远处地形的外观，\n但会增加内存和 GPU 使用。"
t["distanthorizons.config.client.advanced.graphics.quality.transparency"] = "透明度"
t["distanthorizons.config.client.advanced.graphics.quality.lodShading"] = "LOD 着色"
t["distanthorizons.config.client.advanced.graphics.quality.lodShading.@tooltip"] = "定义 LOD 应如何着色。\n可用于改善着色器兼容性。"
t["distanthorizons.config.client.advanced.graphics.quality.grassSideRendering"] = "草方块侧面渲染"
t["distanthorizons.config.client.advanced.graphics.quality.grassSideRendering.@tooltip"] = "草方块 LOD 的侧面和底部应如何渲染？"
t["distanthorizons.config.client.advanced.graphics.quality.ditherDhFade"] = "淡化附近的 DH LOD"
t["distanthorizons.config.client.advanced.graphics.quality.ditherDhFade.@tooltip"] = "如果启用，LOD 会在靠近时逐渐消失。\n如果禁用，LOD 会在相机设定距离处突然消失。\n此设置受原版过绘制预防配置的影响。"
t["distanthorizons.config.client.advanced.graphics.quality.vanillaFadeMode"] = "原版淡化模式"
t["distanthorizons.config.client.advanced.graphics.quality.vanillaFadeMode.@tooltip"] = "原版 Minecraft 应如何淡化到遥远的地平线 LOD？\n\n无：最快，DH 和 MC 渲染之间会有明显的边界。\n单次传递：在 MC 的透明传递后淡化，水下不透明方块不会被淡化。\n双重传递：最慢，在 MC 的不透明和透明传递后淡化，提供最平滑的过渡。"
t["distanthorizons.config.client.advanced.graphics.quality.dhFadeFarClipPlane"] = "在远裁剪平面之前淡化"
t["distanthorizons.config.client.advanced.graphics.quality.dhFadeFarClipPlane.@tooltip"] = "DH 是否应该在到达远裁剪平面之前淡出？\n这有助于防止 DH 云层在远处突然消失。"
t["distanthorizons.config.client.advanced.graphics.quality.brightnessMultiplier"] = "亮度倍率"
t["distanthorizons.config.client.advanced.graphics.quality.brightnessMultiplier.@tooltip"] = "LOD 颜色的亮度。\n\n0 = 黑色\n1 = 正常\n2 = 接近白色"
t["distanthorizons.config.client.advanced.graphics.quality.saturationMultiplier"] = "饱和度倍率"
t["distanthorizons.config.client.advanced.graphics.quality.saturationMultiplier.@tooltip"] = "LOD 颜色的饱和度。\n\n0 = 黑白\n1 = 正常\n2 = 鲜艳"
t["distanthorizons.config.client.advanced.graphics.quality.lodBiomeBlending"] = "生物群系混合"
t["distanthorizons.config.client.advanced.graphics.quality.lodBiomeBlending.@tooltip"] = "这与 LOD 区域的原版生物群系混合设置相同。\n\n注意：任何高于 '0' 的值都会减慢 LOD 加载时间。\n\n'0' 等于原版生物群系混合 '1x1'，\n'1' 等于原版生物群系混合 '3x3'，\n'2' 等于原版生物群系混合 '5x5'..."

# === SSAO ===
t["distanthorizons.config.client.advanced.graphics.enableSsao"] = "启用环境光遮蔽"
t["distanthorizons.config.client.advanced.graphics.enableSsao.@tooltip"] = "环境光遮蔽为方块的照明增加深度。"

# === Generic Rendering ===
t["distanthorizons.config.client.advanced.graphics.genericRendering"] = "通用对象渲染"
t["distanthorizons.config.client.advanced.graphics.genericRendering.enableGenericRendering"] = "启用通用渲染"
t["distanthorizons.config.client.advanced.graphics.genericRendering.enableGenericRendering.@tooltip"] = "如果启用，DH 将渲染非地形对象。\n例如信标光束和云层。"
t["distanthorizons.config.client.advanced.graphics.genericRendering.enableBeaconRendering"] = "启用信标渲染"
t["distanthorizons.config.client.advanced.graphics.genericRendering.beaconRenderHeight"] = "信标渲染高度"
t["distanthorizons.config.client.advanced.graphics.genericRendering.beaconRenderHeight.@tooltip"] = "设置信标将渲染到的最大高度。需要重新加载世界才能生效。"
t["distanthorizons.config.client.advanced.graphics.genericRendering.expandDistantBeacons"] = "扩展远处信标"
t["distanthorizons.config.client.advanced.graphics.genericRendering.expandDistantBeacons.@tooltip"] = "如果启用，LOD 信标光束将在极远处渲染得更宽，\n使它们更容易看到。\n如果禁用，所有 LOD 信标光束将始终只有 1 格宽。"
t["distanthorizons.config.client.advanced.graphics.genericRendering.enableBeaconRendering.@tooltip"] = "如果启用，将渲染 LOD 信标光束。"
t["distanthorizons.config.client.advanced.graphics.genericRendering.enableCloudRendering"] = "启用云层渲染"
t["distanthorizons.config.client.advanced.graphics.genericRendering.enableCloudRendering.@tooltip"] = "如果启用，将渲染 LOD 云层。"
t["distanthorizons.config.client.advanced.graphics.genericRendering.dimensionEnabledCloudRenderingCsv"] = "云层启用维度 CSV 列表"
t["distanthorizons.config.client.advanced.graphics.genericRendering.dimensionEnabledCloudRenderingCsv.@tooltip"] = "DH 云层将渲染的维度资源位置的逗号分隔列表。\n\n示例：\"minecraft:overworld,minecraft:the_end\"\n\n更改需要重新加载世界。"
t["distanthorizons.config.client.advanced.graphics.genericRendering.enableMultiLayerClouds"] = "启用多层云层"
t["distanthorizons.config.client.advanced.graphics.genericRendering.enableMultiLayerClouds.@tooltip"] = "禁用 = DH 将渲染单层云层，如原版 Minecraft。\n启用 = DH 将在不同高度渲染 3 层云层。"

# === Fog ===
t["distanthorizons.config.client.advanced.graphics.fog"] = "雾"
t["distanthorizons.config.client.advanced.graphics.fog.enableDhFog"] = "启用遥远的地平线雾"
t["distanthorizons.config.client.advanced.graphics.fog.enableDhFog.@tooltip"] = "确定是否在 DH LOD 上绘制雾。"
t["distanthorizons.config.client.advanced.graphics.fog.colorMode"] = "雾颜色模式"
t["distanthorizons.config.client.advanced.graphics.fog.colorMode.@tooltip"] = "LOD 上雾的颜色。"
t["distanthorizons.config.client.advanced.graphics.fog.enableVanillaFog"] = "启用原版雾"
t["distanthorizons.config.client.advanced.graphics.fog.enableVanillaFog.@tooltip"] = "§6启用：§r Minecraft 正常渲染雾。\n§6禁用：§r 禁用原版区块上的 Minecraft 雾。\n\n可能影响其他修改雾的模组。"
t["distanthorizons.config.client.advanced.graphics.fog.advancedFog"] = "高级雾选项"
t["distanthorizons.config.client.advanced.graphics.fog.farFogStart"] = "雾起始"
t["distanthorizons.config.client.advanced.graphics.fog.farFogStart.@tooltip"] = "雾应该从哪里开始？\n\n  '0.0'：雾从玩家位置开始。\n  '1.0'：雾起始的圆正好适合 LOD 渲染距离的方形。\n'1.414'：LOD 渲染距离的方形正好适合雾起始的圆。"
t["distanthorizons.config.client.advanced.graphics.fog.farFogEnd"] = "雾结束"
t["distanthorizons.config.client.advanced.graphics.fog.farFogEnd.@tooltip"] = "雾应该在哪里结束？\n\n  '0.0'：雾在玩家位置结束。\n  '1.0'：雾结束的圆正好适合 LOD 渲染距离的方形。\n'1.414'：LOD 渲染距离的方形正好适合雾结束的圆。"
t["distanthorizons.config.client.advanced.graphics.fog.farFogMin"] = "雾最小值"
t["distanthorizons.config.client.advanced.graphics.fog.farFogMin.@tooltip"] = "雾的最小不透明度。"
t["distanthorizons.config.client.advanced.graphics.fog.farFogMax"] = "雾最大值"
t["distanthorizons.config.client.advanced.graphics.fog.farFogMax.@tooltip"] = "雾的最大不透明度。"
t["distanthorizons.config.client.advanced.graphics.fog.farFogFalloff"] = "雾衰减"
t["distanthorizons.config.client.advanced.graphics.fog.farFogFalloff.@tooltip"] = "雾密度变化的速率。"
t["distanthorizons.config.client.advanced.graphics.fog.farFogDensity"] = "雾密度"
t["distanthorizons.config.client.advanced.graphics.fog.farFogDensity.@tooltip"] = "雾的整体密度。"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog"] = "高度雾"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogMixMode"] = "高度雾混合模式"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogMixMode.@tooltip"] = "高度雾如何与远雾混合。"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogDirection"] = "高度雾方向"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogDirection.@tooltip"] = "高度雾应从哪个方向应用。"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogBaseHeight"] = "高度雾基础高度"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogBaseHeight.@tooltip"] = "高度雾开始应用的基础高度。"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogStart"] = "高度雾起始"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogStart.@tooltip"] = "高度雾开始的高度。"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogEnd"] = "高度雾结束"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogEnd.@tooltip"] = "高度雾结束的高度。"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogMin"] = "高度雾最小值"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogMin.@tooltip"] = "高度雾的最小不透明度。"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogMax"] = "高度雾最大值"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogMax.@tooltip"] = "高度雾的最大不透明度。"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogFalloff"] = "高度雾衰减"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogFalloff.@tooltip"] = "高度雾密度变化的速率。"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogDensity"] = "高度雾密度"
t["distanthorizons.config.client.advanced.graphics.fog.heightFog.heightFogDensity.@tooltip"] = "高度雾的整体密度。"

# === Texture ===
t["distanthorizons.config.client.advanced.graphics.texture"] = "纹理"
t["distanthorizons.config.client.advanced.graphics.texture.enableTexturedLods"] = "启用纹理 LOD"
t["distanthorizons.config.client.advanced.graphics.texture.enableTexturedLods.@tooltip"] = "如果启用，LOD 将使用方块纹理进行渲染。\n\n§6注意：§r 启用此设置将大幅增加内存和 GPU 使用。"
t["distanthorizons.config.client.advanced.graphics.texture.maxTexturedLodDetailLevel"] = "最大纹理 LOD 细节级别"
t["distanthorizons.config.client.advanced.graphics.texture.maxTexturedLodDetailLevel.@tooltip"] = "LOD 将使用纹理的最大细节级别。\n\n较低的细节级别将减少内存和 GPU 使用。"
t["distanthorizons.config.client.advanced.graphics.texture.blocksDontRenderTextureCsv"] = "不渲染纹理的方块 CSV"
t["distanthorizons.config.client.advanced.graphics.texture.blocksDontRenderTextureCsv.@tooltip"] = "即使启用了纹理 LOD，这些方块也不会渲染纹理。\n\n示例：\"minecraft:grass_block,minecraft:stone\""
t["distanthorizons.config.client.advanced.graphics.texture.blocksDontUseSideTextureCsv"] = "不使用侧面纹理的方块 CSV"
t["distanthorizons.config.client.advanced.graphics.texture.blocksDontUseSideTextureCsv.@tooltip"] = "这些方块将不会使用侧面纹理进行渲染。"
t["distanthorizons.config.client.advanced.graphics.texture.blockTagsDontUseSideTextureCsv"] = "不使用侧面纹理的方块标签 CSV"
t["distanthorizons.config.client.advanced.graphics.texture.blockTagsDontUseSideTextureCsv.@tooltip"] = "具有这些标签的方块将不会使用侧面纹理进行渲染。"
t["distanthorizons.config.client.advanced.graphics.texture.blocksAlwaysRasterizeTextureCsv"] = "始终栅格化纹理的方块 CSV"
t["distanthorizons.config.client.advanced.graphics.texture.blocksAlwaysRasterizeTextureCsv.@tooltip"] = "这些方块将始终使用栅格化纹理进行渲染。"

# === Noise Texture ===
t["distanthorizons.config.client.advanced.graphics.noiseTexture"] = "噪声纹理"
t["distanthorizons.config.client.advanced.graphics.noiseTexture.enableNoiseTexture"] = "启用噪声纹理"
t["distanthorizons.config.client.advanced.graphics.noiseTexture.enableNoiseTexture.@tooltip"] = "如果启用，LOD 将使用噪声纹理来模拟细节。"
t["distanthorizons.config.client.advanced.graphics.noiseTexture.noiseSteps"] = "噪声步数"
t["distanthorizons.config.client.advanced.graphics.noiseTexture.noiseSteps.@tooltip"] = "噪声纹理的步数。\n\n较高的值会增加细节，但也会增加内存和 GPU 使用。"
t["distanthorizons.config.client.advanced.graphics.noiseTexture.noiseIntensity"] = "噪声强度"
t["distanthorizons.config.client.advanced.graphics.noiseTexture.noiseIntensity.@tooltip"] = "噪声纹理的强度。\n\n较高的值会使噪声更加明显。"
t["distanthorizons.config.client.advanced.graphics.noiseTexture.noiseDropoff"] = "噪声衰减"
t["distanthorizons.config.client.advanced.graphics.noiseTexture.noiseDropoff.@tooltip"] = "噪声纹理的衰减速率。\n\n较高的值会使噪声在远处更快消失。"

# === Culling ===
t["distanthorizons.config.client.advanced.graphics.culling"] = "裁剪"
t["distanthorizons.config.client.advanced.graphics.culling.overdrawPrevention"] = "过绘制预防"
t["distanthorizons.config.client.advanced.graphics.culling.overdrawPrevention.@tooltip"] = "如果启用，DH 将尝试防止过绘制。\n\n过绘制是指同一个像素被多次绘制，\n这会降低性能。"
t["distanthorizons.config.client.advanced.graphics.culling.reduceOverdrawWithFastMovement"] = "快速移动时减少过绘制"
t["distanthorizons.config.client.advanced.graphics.culling.reduceOverdrawWithFastMovement.@tooltip"] = "如果启用，当玩家快速移动时，DH 将减少过绘制。"
t["distanthorizons.config.client.advanced.graphics.culling.enableCaveCulling"] = "启用洞穴裁剪"
t["distanthorizons.config.client.advanced.graphics.culling.enableCaveCulling.@tooltip"] = "如果启用，DH 将裁剪洞穴中的 LOD。\n\n这可以显著提高性能，但可能会导致一些视觉问题。"
t["distanthorizons.config.client.advanced.graphics.culling.caveCullingHeight"] = "洞穴裁剪高度"
t["distanthorizons.config.client.advanced.graphics.culling.caveCullingHeight.@tooltip"] = "洞穴裁剪开始应用的高度。"
t["distanthorizons.config.client.advanced.graphics.culling.disableBeaconDistanceCulling"] = "禁用信标距离裁剪"
t["distanthorizons.config.client.advanced.graphics.culling.disableBeaconDistanceCulling.@tooltip"] = "如果启用，信标将不会因距离而被裁剪。"
t["distanthorizons.config.client.advanced.graphics.culling.disableFrustumCulling"] = "禁用视锥裁剪"
t["distanthorizons.config.client.advanced.graphics.culling.disableFrustumCulling.@tooltip"] = "如果启用，LOD 将不会因视锥而被裁剪。"
t["distanthorizons.config.client.advanced.graphics.culling.disableShadowPassFrustumCulling"] = "禁用阴影传递视锥裁剪"
t["distanthorizons.config.client.advanced.graphics.culling.disableShadowPassFrustumCulling.@tooltip"] = "如果启用，阴影传递将不会因视锥而被裁剪。"
t["distanthorizons.config.client.advanced.graphics.culling.ignoredRenderBlockCsv"] = "忽略渲染的方块 CSV"
t["distanthorizons.config.client.advanced.graphics.culling.ignoredRenderBlockCsv.@tooltip"] = "这些方块将不会被渲染。"
t["distanthorizons.config.client.advanced.graphics.culling.ignoredRenderCaveBlockCsv"] = "忽略渲染的洞穴方块 CSV"
t["distanthorizons.config.client.advanced.graphics.culling.ignoredRenderCaveBlockCsv.@tooltip"] = "这些方块在洞穴中将不会被渲染。"
t["distanthorizons.config.client.advanced.graphics.culling.waterSubSurfaceBlockReplacementCsv"] = "水下地表方块替换 CSV"
t["distanthorizons.config.client.advanced.graphics.culling.waterSubSurfaceBlockReplacementCsv.@tooltip"] = "这些方块将在水下被替换。"
t["distanthorizons.config.client.advanced.graphics.culling.waterSurfaceBlockReplacementCsv"] = "水面方块替换 CSV"
t["distanthorizons.config.client.advanced.graphics.culling.waterSurfaceBlockReplacementCsv.@tooltip"] = "这些方块将在水面被替换。"
t["distanthorizons.config.client.advanced.graphics.culling.blocksToIgnore"] = "忽略的方块"
t["distanthorizons.config.client.advanced.graphics.culling.blocksToIgnore.@tooltip"] = "这些方块将被忽略。"
t["distanthorizons.config.client.advanced.graphics.culling.tintWithAvoidedBlocks"] = "使用被避免的方块进行染色"
t["distanthorizons.config.client.advanced.graphics.culling.tintWithAvoidedBlocks.@tooltip"] = "如果启用，被避免的方块将被染色。"

# === Override Vanilla ===
t["distanthorizons.config.client.advanced.graphics.overrideVanillaGraphicsSettings"] = "覆盖原版图形设置"
t["distanthorizons.config.client.advanced.graphics.overrideVanillaGraphicsSettings.@tooltip"] = "如果启用，DH 将覆盖一些原版图形设置。"

# === Experimental ===
t["distanthorizons.config.client.advanced.graphics.experimental"] = "实验性"
t["distanthorizons.config.client.advanced.graphics.experimental.earthCurveRatio"] = "地球曲率比率"
t["distanthorizons.config.client.advanced.graphics.experimental.earthCurveRatio.@tooltip"] = "地球曲率的比率。\n\n0 = 平面\n1 = 真实地球曲率"
t["distanthorizons.config.client.advanced.graphics.experimental.ignoredDimensionCsv"] = "忽略的维度 CSV"
t["distanthorizons.config.client.advanced.graphics.experimental.ignoredDimensionCsv.@tooltip"] = "这些维度将被忽略。"
t["distanthorizons.config.client.advanced.graphics.experimental.renderingEngine"] = "渲染引擎"
t["distanthorizons.config.client.advanced.graphics.experimental.renderingEngine.@tooltip"] = "选择要使用的渲染引擎。"

# === Auto Updater ===
t["distanthorizons.config.client.advanced.autoUpdater"] = "自动更新器"
t["distanthorizons.config.client.advanced.autoUpdater.enableAutoUpdater"] = "启用自动更新器"
t["distanthorizons.config.client.advanced.autoUpdater.enableSilentUpdates"] = "启用静默更新"
t["distanthorizons.config.client.advanced.autoUpdater.enableSilentUpdates.@tooltip"] = "如果启用，更新将在后台静默进行。"
t["distanthorizons.config.client.advanced.autoUpdater.updateBranch"] = "更新分支"
t["distanthorizons.config.client.advanced.autoUpdater.updateBranch.@tooltip"] = "选择要使用的更新分支。"

# === Multiplayer ===
t["distanthorizons.config.client.advanced.multiplayer"] = "多人游戏"
t["distanthorizons.config.client.advanced.multiplayer.serverFolderNameMode"] = "服务器文件夹名称模式"
t["distanthorizons.config.client.advanced.multiplayer.serverFolderNameMode.@tooltip"] = "选择服务器文件夹名称的显示方式。"

# === Debugging ===
t["distanthorizons.config.client.advanced.debugging"] = "调试"
t["distanthorizons.config.client.advanced.debugging.rendererMode"] = "渲染器模式"
t["distanthorizons.config.client.advanced.debugging.debugRenderingColors"] = "调试渲染颜色"
t["distanthorizons.config.client.advanced.debugging.lodOnlyMode"] = "仅 LOD 模式"
t["distanhorizons.config.client.advanced.debugging.lodOnlyMode.@tooltip"] = "如果启用，只会渲染 LOD。"
t["distanthorizons.config.client.advanced.debugging.renderWireframe"] = "渲染线框"
t["distanthorizons.config.client.advanced.debugging.renderWireframe.@tooltip"] = "如果启用，将渲染线框。"
t["distanthorizons.config.client.advanced.debugging.enableDebugKeybindings"] = "启用调试按键绑定"
t["distanthorizons.config.client.advanced.debugging.enableDebugKeybindings.@tooltip"] = "如果启用，将启用调试按键绑定。"
t["distanthorizons.config.client.advanced.debugging.enableWhiteWorld"] = "启用白色世界"
t["distanthorizons.config.client.advanced.debugging.enableWhiteWorld.@tooltip"] = "如果启用，世界将变为白色。"
t["distanthorizons.config.client.advanced.debugging.showOverlappingQuadErrors"] = "显示重叠四边形错误"
t["distanthorizons.config.client.advanced.debugging.showOverlappingQuadErrors.@tooltip"] = "如果启用，将显示重叠四边形错误。"
t["distanthorizons.config.client.advanced.debugging.logBufferGarbageCollection"] = "日志缓冲区垃圾回收"
t["distanthorizons.config.client.advanced.debugging.logBufferGarbageCollection.@tooltip"] = "如果启用，将记录缓冲区垃圾回收。"
t["distanthorizons.config.client.advanced.debugging.allowUnsafeValues"] = "允许不安全值"
t["distanthorizons.config.client.advanced.debugging.allowUnsafeValues.@tooltip"] = "如果启用，将允许不安全值。"
t["distanthorizons.config.client.advanced.debugging.debugWireframe"] = "调试线框"
t["distanthorizons.config.client.advanced.debugging.debugWireframe.enableRendering"] = "启用渲染"
t["distanthorizons.config.client.advanced.debugging.debugWireframe.enableRendering.@tooltip"] = "如果启用，将渲染调试线框。"
t["distanthorizons.config.client.advanced.debugging.debugWireframe.showWorldGenQueue"] = "显示世界生成队列"
t["distanthorizons.config.client.advanced.debugging.debugWireframe.showNetworkSyncOnLoadQueue"] = "显示网络同步加载队列"
t["distanthorizons.config.client.advanced.debugging.debugWireframe.showRenderSectionStatus"] = "显示渲染部分状态"
t["distanthorizons.config.client.advanced.debugging.debugWireframe.showRenderSectionToggling"] = "显示渲染部分切换"
t["distanthorizons.config.client.advanced.debugging.debugWireframe.showQuadTreeRenderStatus"] = "显示四叉树渲染状态"
t["distanthorizons.config.client.advanced.debugging.debugWireframe.showFullDataUpdateStatus"] = "显示完整数据更新状态"

# === OpenGL ===
t["distanthorizons.config.client.advanced.debugging.openGl"] = "OpenGL"
t["distanthorizons.config.client.advanced.debugging.openGl.overrideVanillaGLLogger"] = "覆盖原版 OpenGL 日志器"
t["distanthorizons.config.client.advanced.debugging.openGl.overrideVanillaGLLogger.@tooltip"] = "如果启用，将覆盖原版 OpenGL 日志器。"
t["distanthorizons.config.client.advanced.debugging.openGl.onlyLogGlErrorsOnce"] = "仅记录一次 OpenGL 错误"
t["distanthorizons.config.client.advanced.debugging.openGl.onlyLogGlErrorsOnce.@tooltip"] = "如果启用，每个 OpenGL 错误只会记录一次。"
t["distanthorizons.config.client.advanced.debugging.openGl.glErrorHandlingMode"] = "OpenGL 错误处理模式"
t["distanthorizons.config.client.advanced.debugging.openGl.glErrorHandlingMode.@tooltip"] = "选择 OpenGL 错误处理模式。"

# === Column Builder Debugging ===
t["distanthorizons.config.client.advanced.debugging.columnBuilderDebugging"] = "列构建器调试"
t["distanthorizons.config.client.advanced.debugging.columnBuilderDebugging.columnBuilderDebugEnable"] = "启用列构建器调试"
t["distanthorizons.config.client.advanced.debugging.columnBuilderDebugging.columnBuilderDebugDetailLevel"] = "列构建器调试细节级别"
t["distanthorizons.config.client.advanced.debugging.columnBuilderDebugging.columnBuilderDebugXPos"] = "列构建器调试 X 位置"
t["distanthorizons.config.client.advanced.debugging.columnBuilderDebugging.columnBuilderDebugZPos"] = "列构建器调试 Z 位置"
t["distanthorizons.config.client.advanced.debugging.columnBuilderDebugging.columnBuilderDebugXRow"] = "列构建器调试 X 行"
t["distanthorizons.config.client.advanced.debugging.columnBuilderDebugging.columnBuilderDebugZRow"] = "列构建器调试 Z 行"
t["distanthorizons.config.client.advanced.debugging.columnBuilderDebugging.columnBuilderDebugColumnIndex"] = "列构建器调试列索引"

# === Position Finder Debugging ===
t["distanthorizons.config.client.advanced.debugging.positionFinderDebugging"] = "位置查找器调试"
t["distanthorizons.config.client.advanced.debugging.positionFinderDebugging.positionFinderEnable"] = "启用位置查找器"
t["distanthorizons.config.client.advanced.debugging.positionFinderDebugging.positionFinderDetailLevel"] = "位置查找器细节级别"
t["distanthorizons.config.client.advanced.debugging.positionFinderDebugging.positionFinderXPos"] = "位置查找器 X 位置"
t["distanthorizons.config.client.advanced.debugging.positionFinderDebugging.positionFinderZPos"] = "位置查找器 Z 位置"
t["distanthorizons.config.client.advanced.debugging.positionFinderDebugging.positionFinderMinBlockY"] = "位置查找器最小方块 Y"
t["distanthorizons.config.client.advanced.debugging.positionFinderDebugging.positionFinderMaxBlockY"] = "位置查找器最大方块 Y"
t["distanthorizons.config.client.advanced.debugging.positionFinderDebugging.positionFinderMarginPercent"] = "位置查找器边距百分比"

# === F3 Screen ===
t["distanthorizons.config.client.advanced.debugging.f3Screen"] = "F3 屏幕"
t["distanthorizons.config.client.advanced.debugging.f3Screen.showPlayerPos"] = "显示玩家位置"
t["distanthorizons.config.client.advanced.debugging.f3Screen.playerPosSectionDetailLevel"] = "玩家位置部分细节级别"
t["distanthorizons.config.client.advanced.debugging.f3Screen.showThreadPools"] = "显示线程池"
t["distanthorizons.config.client.advanced.debugging.f3Screen.showRenderThreadTasks"] = "显示渲染线程任务"
t["distanthorizons.config.client.advanced.debugging.f3Screen.showCombinedObjectPools"] = "显示组合对象池"
t["distanthorizons.config.client.advanced.debugging.f3Screen.showSeparatedObjectPools"] = "显示分离对象池"
t["distanthorizons.config.client.advanced.debugging.f3Screen.showQueuedChunkUpdateCount"] = "显示排队区块更新计数"
t["distanthorizons.config.client.advanced.debugging.f3Screen.showLevelStatus"] = "显示级别状态"
t["distanthorizons.config.client.advanced.debugging.f3Screen.onlyShowRenderingLevels"] = "仅显示渲染级别"

# === Example Config Screen ===
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen"] = "示例配置屏幕"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.debugConfigScreenNote"] = "调试配置屏幕注释"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.boolTest"] = "布尔测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.byteTest"] = "字节测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.intTest"] = "整数测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.doubleTest"] = "双精度测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.shortTest"] = "短整数测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.longTest"] = "长整数测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.floatTest"] = "浮点数测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.stringTest"] = "字符串测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.uiButtonTest"] = "UI 按钮测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.listTest"] = "列表测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.mapTest"] = "映射测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.categoryTest"] = "类别测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.linkableTest"] = "可链接测试"
t["distanthorizons.config.client.advanced.debugging.exampleConfigScreen.linkableTest.@tooltip"] = "这是一个可链接的测试。"

# === Config Common ===
t["distanthorizons.config.common"] = "通用"
t["distanthorizons.config.common.worldGenerator"] = "世界生成器"
t["distanthorizons.config.common.worldGenerator.enableDistantGeneration"] = "启用远程生成"
t["distanthorizons.config.common.worldGenerator.enableDistantGeneration.@tooltip"] = "如果启用，将启用远程生成。"
t["distanthorizons.config.common.worldGenerator.distantGeneratorMode"] = "远程生成器模式"
t["distanthorizons.config.common.worldGenerator.distantGeneratorMode.@tooltip"] = "选择远程生成器模式。"
t["distanthorizons.config.common.worldGenerator.showGenerationProgress"] = "显示生成进度"
t["distanthorizons.config.common.worldGenerator.showGenerationProgress.@tooltip"] = "如果启用，将显示生成进度。"
t["distanthorizons.config.common.worldGenerator.generationProgressDisplayIntervalInSeconds"] = "生成进度显示间隔（秒）"
t["distanthorizons.config.common.worldGenerator.generationProgressDisplayIntervalInSeconds.@tooltip"] = "生成进度显示的间隔（秒）。"
t["distanthorizons.config.common.worldGenerator.generationProgressDisableMessageDisplayTimeInSeconds"] = "生成进度禁用消息显示时间（秒）"
t["distanthorizons.config.common.worldGenerator.generationProgressDisableMessageDisplayTimeInSeconds.@tooltip"] = "生成进度禁用消息显示的时间（秒）。"
t["distanthorizons.config.common.worldGenerator.generationProgressIncludeChunksPerSecond"] = "生成进度包含每秒区块数"
t["distanthorizons.config.common.worldGenerator.generationProgressIncludeChunksPerSecond.@tooltip"] = "如果启用，生成进度将包含每秒区块数。"

# === LOD Building ===
t["distanthorizons.config.common.lodBuilding"] = "LOD 构建"
t["distanthorizons.config.common.lodBuilding.disableUnchangedChunkCheck"] = "禁用未更改区块检查"
t["distanthorizons.config.common.lodBuilding.disableUnchangedChunkCheck.@tooltip"] = "如果启用，将禁用未更改区块检查。"
t["distanthorizons.config.common.lodBuilding.dataCompression"] = "数据压缩"
t["distanthorizons.config.common.lodBuilding.dataCompression.@tooltip"] = "选择数据压缩模式。"
t["distanthorizons.config.common.lodBuilding.worldCompression"] = "世界压缩"
t["distanthorizons.config.common.lodBuilding.worldCompression.@tooltip"] = "选择世界压缩模式。"
t["distanthorizons.config.common.lodBuilding.experimental"] = "实验性"
t["distanthorizons.config.common.lodBuilding.experimental.upsampleLowerDetailLodsToFillHoles"] = "上采样低细节 LOD 以填补空洞"
t["distanthorizons.config.common.lodBuilding.experimental.upsampleLowerDetailLodsToFillHoles.@tooltip"] = "如果启用，将上采样低细节 LOD 以填补空洞。"

# === MultiThreading ===
t["distanthorizons.config.common.multiThreading"] = "多线程"
t["distanthorizons.config.common.multiThreading.numberOfThreads"] = "线程数"
t["distanthorizons.config.common.multiThreading.numberOfThreads.@tooltip"] = "选择线程数。"
t["distanthorizons.config.common.multiThreading.threadRunTimeRatio"] = "线程运行时间比率"
t["distanthorizons.config.common.multiThreading.threadPriority"] = "线程优先级"
t["distanthorizons.config.common.multiThreading.threadPriority.@tooltip"] = "选择线程优先级。"

# === Logging ===
t["distanthorizons.config.common.logging"] = "日志"
t["distanthorizons.config.common.logging.@tooltip"] = "配置日志设置。"
t["distanthorizons.config.common.logging.globalFileMaxLevel"] = "全局文件最大级别"
t["distanthorizons.config.common.logging.globalChatMaxLevel"] = "全局聊天最大级别"
t["distanthorizons.config.common.logging.logWorldGenEventToFile"] = "记录世界生成事件到文件"
t["distanthorizons.config.common.logging.logWorldGenChunkLoadEventToFile"] = "记录世界生成区块加载事件到文件"
t["distanthorizons.config.common.logging.logRendererEventToFile"] = "记录渲染器事件到文件"
t["distanthorizons.config.common.logging.logRendererGLEventToFile"] = "记录渲染器 OpenGL 事件到文件"
t["distanthorizons.config.common.logging.logRendererGLEventToChat"] = "记录渲染器 OpenGL 事件到聊天"
t["distanthorizons.config.common.logging.logNetworkEventToFile"] = "记录网络事件到文件"
t["distanthorizons.config.common.logging.logConnectionConfigChangesToFile"] = "记录连接配置更改到文件"

# === Logging Warnings ===
t["distanthorizons.config.common.logging.warning"] = "警告"
t["distanthorizons.config.common.logging.warning.showLowMemoryWarningOnStartup"] = "启动时显示低内存警告"
t["distanthorizons.config.common.logging.warning.showPoolInsufficientMemoryWarning"] = "显示池内存不足警告"
t["distanthorizons.config.common.logging.warning.showPoolInsufficientMemoryWarning.@tooltip"] = "如果启用，将显示池内存不足警告。"
t["distanthorizons.config.common.logging.warning.showHighVanillaRenderDistanceWarning"] = "显示高原版渲染距离警告"
t["distanthorizons.config.common.logging.warning.showReplayWarningOnStartup"] = "启动时显示回放警告"
t["distanthorizons.config.common.logging.warning.showUpdateQueueOverloadedChatWarning"] = "显示更新队列过载聊天警告"
t["distanthorizons.config.common.logging.warning.showSlowWorldGenSettingWarnings"] = "显示慢世界生成设置警告"
t["distanthorizons.config.common.logging.warning.showModCompatibilityWarningsOnStartup"] = "启动时显示模组兼容性警告"
t["distanthorizons.config.common.logging.warning.showDeprecatedRendererWarningOnStartup"] = "启动时显示弃用渲染器警告"
t["distanthorizons.config.common.logging.warning.logGarbageCollectorWarning"] = "记录垃圾回收器警告"
t["distanthorizons.config.common.logging.warning.showGarbageCollectorWarning"] = "显示垃圾回收器警告"
t["distanthorizons.config.common.logging.warning.logExplicitGcDisabledWarning"] = "记录显式 GC 禁用警告"
t["distanthorizons.config.common.logging.warning.showExplicitGcDisabledWarning"] = "显示显式 GC 禁用警告"

# === Config Server ===
t["distanthorizons.config.server"] = "服务器"
t["distanthorizons.config.server.sendLevelKeys"] = "发送级别密钥"
t["distanthorizons.config.server.sendLevelKeys.@tooltip"] = "如果启用，将发送级别密钥。"
t["distanthorizons.config.server.levelKeyPrefix"] = "级别密钥前缀"
t["distanthorizons.config.server.levelKeyPrefix.@tooltip"] = "级别密钥的前缀。"
t["distanthorizons.config.server.enableServerGeneration"] = "启用服务器生成"
t["distanthorizons.config.server.enableServerGeneration.@tooltip"] = "如果启用，将启用服务器生成。"
t["distanthorizons.config.server.generationRequestRateLimit"] = "生成请求速率限制"
t["distanthorizons.config.server.generationRequestRateLimit.@tooltip"] = "生成请求的速率限制。"
t["distanthorizons.config.server.maxGenerationRequestDistance"] = "最大生成请求距离"
t["distanthorizons.config.server.maxGenerationRequestDistance.@tooltip"] = "最大生成请求距离。"
t["distanthorizons.config.server.enableRealTimeUpdates"] = "启用实时更新"
t["distanthorizons.config.server.enableRealTimeUpdates.@tooltip"] = "如果启用，将启用实时更新。"
t["distanthorizons.config.server.realTimeUpdateDistanceRadiusInChunks"] = "实时更新距离半径（区块）"
t["distanthorizons.config.server.realTimeUpdateDistanceRadiusInChunks.@tooltip"] = "实时更新距离半径（区块）。"
t["distanthorizons.config.server.synchronizeOnLoad"] = "加载时同步"
t["distanthorizons.config.server.synchronizeOnLoad.@tooltip"] = "如果启用，将在加载时同步。"
t["distanthorizons.config.server.syncOnLoadRateLimit"] = "加载时同步速率限制"
t["distanthorizons.config.server.syncOnLoadRateLimit.@tooltip"] = "加载时同步的速率限制。"
t["distanthorizons.config.server.maxSyncOnLoadRequestDistance"] = "最大加载时同步请求距离"
t["distanthorizons.config.server.maxSyncOnLoadRequestDistance.@tooltip"] = "最大加载时同步请求距离。"
t["distanthorizons.config.server.playerBandwidthLimit"] = "玩家带宽限制"
t["distanthorizons.config.server.playerBandwidthLimit.@tooltip"] = "玩家带宽限制。"
t["distanthorizons.config.server.globalBandwidthLimit"] = "全局带宽限制"
t["distanthorizons.config.server.globalBandwidthLimit.@tooltip"] = "全局带宽限制。"
t["distanthorizons.config.server.enableAdaptiveTransferSpeed"] = "启用自适应传输速度"
t["distanthorizons.config.server.enableAdaptiveTransferSpeed.@tooltip"] = "如果启用，将启用自适应传输速度。"
t["distanthorizons.config.server.experimental"] = "实验性"
t["distanthorizons.config.server.experimental.enableNSizedGeneration"] = "启用 N 大小生成"
t["distanthorizons.config.server.experimental.enableNSizedGeneration.@tooltip"] = "如果启用，将启用 N 大小生成。"

# === Enums ===
t["distanthorizons.config.enum.EDhApiQualityPreset.CUSTOM"] = "自定义"
t["distanthorizons.config.enum.EDhApiQualityPreset.MINIMUM"] = "最低"
t["distanthorizons.config.enum.EDhApiQualityPreset.LOW"] = "低"
t["distanthorizons.config.enum.EDhApiQualityPreset.MEDIUM"] = "中"
t["distanthorizons.config.enum.EDhApiQualityPreset.HIGH"] = "高"
t["distanthorizons.config.enum.EDhApiQualityPreset.EXTREME"] = "极高"
t["distanthorizons.config.enum.EDhApiThreadPreset.CUSTOM"] = "自定义"
t["distanthorizons.config.enum.EDhApiThreadPreset.MINIMAL_IMPACT"] = "最小影响"
t["distanthorizons.config.enum.EDhApiThreadPreset.LOW_IMPACT"] = "低影响"
t["distanthorizons.config.enum.EDhApiThreadPreset.BALANCED"] = "平衡"
t["distanthorizons.config.enum.EDhApiThreadPreset.AGGRESSIVE"] = "激进"
t["distanthorizons.config.enum.EDhApiThreadPreset.I_PAID_FOR_THE_WHOLE_CPU"] = "我为整个 CPU 付了钱"
t["distanthorizons.config.enum.EDhApiMaxHorizontalResolution.BLOCK"] = "方块"
t["distanthorizons.config.enum.EDhApiMaxHorizontalResolution.TWO_BLOCKS"] = "两个方块"
t["distanthorizons.config.enum.EDhApiMaxHorizontalResolution.FOUR_BLOCKS"] = "四个方块"
t["distanthorizons.config.enum.EDhApiMaxHorizontalResolution.HALF_CHUNK"] = "半区块"
t["distanthorizons.config.enum.EDhApiMaxHorizontalResolution.CHUNK"] = "区块"
t["distanthorizons.config.enum.EDhApiMcRenderingFadeMode.NONE"] = "无"
t["distanthorizons.config.enum.EDhApiMcRenderingFadeMode.SINGLE_PASS"] = "单次传递"
t["distanthorizons.config.enum.EDhApiMcRenderingFadeMode.DOUBLE_PASS"] = "双重传递"
t["distanthorizons.config.enum.EDhApiVerticalQuality.HEIGHT_MAP"] = "高度图"
t["distanthorizons.config.enum.EDhApiVerticalQuality.LOW"] = "低"
t["distanthorizons.config.enum.EDhApiVerticalQuality.MEDIUM"] = "中"
t["distanthorizons.config.enum.EDhApiVerticalQuality.HIGH"] = "高"
t["distanthorizons.config.enum.EDhApiVerticalQuality.VERY_HIGH"] = "非常高"
t["distanthorizons.config.enum.EDhApiVerticalQuality.EXTREME"] = "极高"
t["distanthorizons.config.enum.EDhApiVerticalQuality.PIXEL_ART"] = "像素艺术"
t["distanthorizons.config.enum.EDhApiHorizontalQuality.LOWEST"] = "最低"
t["distanthorizons.config.enum.EDhApiHorizontalQuality.LOW"] = "低"
t["distanthorizons.config.enum.EDhApiHorizontalQuality.MEDIUM"] = "中"
t["distanthorizons.config.enum.EDhApiHorizontalQuality.HIGH"] = "高"
t["distanthorizons.config.enum.EDhApiHorizontalQuality.EXTREME"] = "极高"
t["distanthorizons.config.enum.EDhApiTransparency.DISABLED"] = "禁用"
t["distanthorizons.config.enum.EDhApiTransparency.COMPLETE"] = "完整"
t["distanthorizons.config.enum.EDhApiFogColorMode.USE_WORLD_FOG_COLOR"] = "使用世界雾颜色"
t["distanthorizons.config.enum.EDhApiFogColorMode.USE_SKY_COLOR"] = "使用天空颜色"
t["distanthorizons.config.enum.EDhApiFogFalloff.LINEAR"] = "线性"
t["distanthorizons.config.enum.EDhApiFogFalloff.EXPONENTIAL"] = "指数"
t["distanthorizons.config.enum.EDhApiFogFalloff.EXPONENTIAL_SQUARED"] = "指数平方"
t["distanthorizons.config.enum.EDhApiHeightFogMixMode.SPHERICAL"] = "球形"
t["distanthorizons.config.enum.EDhApiHeightFogMixMode.CYLINDRICAL"] = "圆柱形"
t["distanthorizons.config.enum.EDhApiHeightFogMixMode.ADDITION"] = "加法"
t["distanthorizons.config.enum.EDhApiHeightFogMixMode.MAX"] = "最大值"
t["distanthorizons.config.enum.EDhApiHeightFogMixMode.MULTIPLY"] = "乘法"
t["distanthorizons.config.enum.EDhApiHeightFogMixMode.INVERSE_MULTIPLY"] = "逆乘法"
t["distanthorizons.config.enum.EDhApiHeightFogMixMode.LIMITED_ADDITION"] = "有限加法"
t["distanthorizons.config.enum.EDhApiHeightFogMixMode.MULTIPLY_ADDITION"] = "乘法加法"
t["distanthorizons.config.enum.EDhApiHeightFogMixMode.INVERSE_MULTIPLY_ADDITION"] = "逆乘法加法"
t["distanthorizons.config.enum.EDhApiHeightFogMixMode.AVERAGE"] = "平均"
t["distanthorizons.config.enum.EDhApiHeightFogDirection.ABOVE_CAMERA"] = "相机上方"
t["distanthorizons.config.enum.EDhApiHeightFogDirection.BELOW_CAMERA"] = "相机下方"
t["distanthorizons.config.enum.EDhApiHeightFogDirection.ABOVE_AND_BELOW_CAMERA"] = "相机上下方"
t["distanthorizons.config.enum.EDhApiHeightFogDirection.ABOVE_SET_HEIGHT"] = "设定高度上方"
t["distanthorizons.config.enum.EDhApiHeightFogDirection.BELOW_SET_HEIGHT"] = "设定高度下方"
t["distanthorizons.config.enum.EDhApiHeightFogDirection.ABOVE_AND_BELOW_SET_HEIGHT"] = "设定高度上下方"
t["distanthorizons.config.enum.EDhApiDistantGeneratorMode.NONE"] = "无"
t["distanthorizons.config.enum.EDhApiDistantGeneratorMode.PRE_EXISTING_ONLY"] = "仅预存在"
t["distanthorizons.config.enum.EDhApiDistantGeneratorMode.BIOME_ONLY"] = "仅生物群系"
t["distanthorizons.config.enum.EDhApiDistantGeneratorMode.BIOME_ONLY_SIMULATE_HEIGHT"] = "仅生物群系（模拟高度）"
t["distanthorizons.config.enum.EDhApiDistantGeneratorMode.SURFACE"] = "地表"
t["distanthorizons.config.enum.EDhApiDistantGeneratorMode.FEATURES"] = "特征"
t["distanthorizons.config.enum.EDhApiDistantGeneratorMode.INTERNAL_SERVER"] = "内部服务器"
t["distanthorizons.config.enum.EDhApiDistantGeneratorProgressDisplayLocation.OVERLAY"] = "叠加层"
t["distanthorizons.config.enum.EDhApiDistantGeneratorProgressDisplayLocation.CHAT"] = "聊天"
t["distanthorizons.config.enum.EDhApiDistantGeneratorProgressDisplayLocation.LOG"] = "日志"
t["distanthorizons.config.enum.EDhApiDistantGeneratorProgressDisplayLocation.DISABLED"] = "禁用"
t["distanthorizons.config.enum.EDhApiDataCompressionMode.UNCOMPRESSED"] = "未压缩"
t["distanthorizons.config.enum.EDhApiDataCompressionMode.LZ4"] = "LZ4"
t["distanthorizons.config.enum.EDhApiDataCompressionMode.Z_STD_BLOCK"] = "Z STD 块"
t["distanthorizons.config.enum.EDhApiDataCompressionMode.Z_STD_STREAM"] = "Z STD 流"
t["distanthorizons.config.enum.EDhApiDataCompressionMode.LZMA2"] = "LZMA2"
t["distanthorizons.config.enum.EDhApiWorldCompressionMode.MERGE_SAME_BLOCKS"] = "合并相同方块"
t["distanthorizons.config.enum.EDhApiWorldCompressionMode.VISUALLY_EQUAL"] = "视觉相等"
t["distanthorizons.config.enum.EDhApiBlocksToAvoid.NONE"] = "无"
t["distanthorizons.config.enum.EDhApiBlocksToAvoid.NON_COLLIDING"] = "非碰撞"
t["distanthorizons.config.enum.EDhApiServerFolderNameMode.NAME_ONLY"] = "仅名称"
t["distanthorizons.config.enum.EDhApiServerFolderNameMode.IP_ONLY"] = "仅 IP"
t["distanthorizons.config.enum.EDhApiServerFolderNameMode.NAME_IP"] = "名称 + IP"
t["distanthorizons.config.enum.EDhApiServerFolderNameMode.NAME_IP_PORT"] = "名称 + IP + 端口"
t["distanthorizons.config.enum.EDhApiServerFolderNameMode.NAME_IP_PORT_MC_VERSION"] = "名称 + IP + 端口 + MC 版本"
t["distanthorizons.config.enum.EDhApiRendererMode.DEFAULT"] = "默认"
t["distanthorizons.config.enum.EDhApiRendererMode.DEBUG_TRIANGLE"] = "调试三角形"
t["distanthorizons.config.enum.EDhApiRendererMode.DISABLED"] = "禁用"
t["distanthorizons.config.enum.EDhApiDebugRendering.OFF"] = "关闭"
t["distanthorizons.config.enum.EDhApiDebugRendering.SHOW_DETAIL"] = "显示细节"
t["distanthorizons.config.enum.EDhApiDebugRendering.SHOW_GENMODE"] = "显示生成模式"
t["distanthorizons.config.enum.EDhApiDebugRendering.SHOW_BLOCK_MATERIAL"] = "显示方块材质"
t["distanthorizons.config.enum.EDhApiDebugRendering.SHOW_OVERLAPPING_QUADS"] = "显示重叠四边形"
t["distanthorizons.config.enum.EDhApiDebugRendering.SHOW_RENDER_SOURCE_FLAG"] = "显示渲染源标志"
t["distanthorizons.config.enum.EDhApiGLErrorHandlingMode.IGNORE"] = "忽略"
t["distanthorizons.config.enum.EDhApiGLErrorHandlingMode.LOG"] = "记录"
t["distanthorizons.config.enum.EDhApiGLErrorHandlingMode.LOG_THROW"] = "记录并抛出"
t["distanthorizons.config.enum.EDhApiLoggerLevel.ALL"] = "全部"
t["distanthorizons.config.enum.EDhApiLoggerLevel.DEBUG"] = "调试"
t["distanthorizons.config.enum.EDhApiLoggerLevel.INFO"] = "信息"
t["distanthorizons.config.enum.EDhApiLoggerLevel.WARN"] = "警告"
t["distanthorizons.config.enum.EDhApiLoggerLevel.ERROR"] = "错误"
t["distanthorizons.config.enum.EDhApiLoggerLevel.DISABLED"] = "禁用"
t["distanthorizons.config.enum.EDhApiLodShading.AUTO"] = "自动"
t["distanthorizons.config.enum.EDhApiLodShading.ENABLED"] = "启用"
t["distanthorizons.config.enum.EDhApiLodShading.DISABLED"] = "禁用"
t["distanthorizons.config.enum.EDhApiUpdateBranch.STABLE"] = "稳定版"
t["distanthorizons.config.enum.EDhApiUpdateBranch.NIGHTLY"] = " nightly"
t["distanthorizons.config.enum.EDhApiUpdateBranch.AUTO"] = "自动"
t["distanthorizons.config.enum.EDhApiGrassSideRendering.AS_GRASS"] = "作为草"
t["distanthorizons.config.enum.EDhApiGrassSideRendering.FADE_TO_DIRT"] = "淡化为泥土"
t["distanthorizons.config.enum.EDhApiGrassSideRendering.AS_DIRT"] = "作为泥土"
t["distanthorizons.config.enum.EDhApiRenderingEngine.AUTO"] = "自动"
t["distanthorizons.config.enum.EDhApiRenderingEngine.OPEN_GL"] = "OpenGL"
t["distanthorizons.config.enum.EDhApiRenderingEngine.BLAZE_3D"] = "Blaze 3D"

# Verify
missing = [k for k in en if k not in t]
extra = [k for k in t if k not in en]
print(f"英文键数: {len(en)}")
print(f"中文键数: {len(t)}")
print(f"缺失: {len(missing)}")
print(f"多余: {len(extra)}")
if missing:
    print("MISSING:")
    for k in missing:
        print(f"  {k}")

# Save
output_path = r"D:/Minecraft_III/Minecraft-Server/食韵筑家专用材质包v1.21.1/assets/distanthorizons/lang/zh_cn.json"
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    json.dump(t, f, ensure_ascii=False, indent=0)
print(f"\n文件已保存: {output_path}")

# Verify JSON
with open(output_path, 'r', encoding='utf-8') as f:
    verify = json.load(f)
print(f"JSON 有效: {len(verify)} 个键")

# Cleanup
os.remove('temp_distant_en_us.json')
print("完成")
